ReAdW	--mzXML	10G_Laubextrakt.raw	10G_Laubextrakt.mzXML
ReAdW	--mzXML	11G_Laubextrakt.raw	11G_Laubextrakt.mzXML
ReAdW	--mzXML	12G_1_Laubextrakt.raw	12G_1_Laubextrakt.mzXML
ReAdW	--mzXML	12G_2_Laubextrakt.raw	12G_2_Laubextrakt.mzXML
ReAdW	--mzXML	12G_Laubextrakt.raw	12G_Laubextrakt.mzXML
ReAdW	--mzXML	1BFE0.raw	1BFE0.mzXML
ReAdW	--mzXML	2BFE_1_Laubextrakt.raw	2BFE_1_Laubextrakt.mzXML
ReAdW	--mzXML	2BFE_Laubextrakt.raw	2BFE_Laubextrakt.mzXML
ReAdW	--mzXML	3BFE_Laubextrakt.raw	3BFE_Laubextrakt.mzXML
ReAdW	--mzXML	4B_Laubextrakt.raw	4B_Laubextrakt.mzXML
ReAdW	--mzXML	5B_1_Laubextrakt.raw	5B_1_Laubextrakt.mzXML
ReAdW	--mzXML	5B_Laubextrakt.raw	5B_Laubextrakt.mzXML
ReAdW	--mzXML	6B_Laubextrakt.raw	6B_Laubextrakt.mzXML
ReAdW	--mzXML	7GFE0_1_Laubextrakt.raw	7GFE0_1_Laubextrakt.mzXML
ReAdW	--mzXML	7GFE0_Laubextrakt.raw	7GFE0_Laubextrakt.mzXML
ReAdW	--mzXML	8GFE_Laubextrakt.raw	8GFE_Laubextrakt.mzXML
ReAdW	--mzXML	9GFE_Laubextrakt.raw	9GFE_Laubextrakt.mzXML
ReAdW	--mzXML	W29112010_Laubextrakt.raw	W29112010_Laubextrakt.mzXML
ReAdW	--mzXML	WETACMEOH_ETOH_Laubextrakt.raw	WETACMEOH_ETOH_Laubextrakt.mzXML
ReAdW	--mzXML	WETACMEOH_MQ_Laubextrakt.raw	WETACMEOH_MQ_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_ETOH_IT_Laubextrakt.raw	WPETACMEOH_ETOH_IT_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_ETOH_Laubextrakt.raw	WPETACMEOH_ETOH_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_G_Laubextrakt.raw	WPETACMEOH_G_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_MQ1_Laubextrakt.raw	WPETACMEOH_MQ1_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_MQ1_Laubextrakt_110719133211.raw	WPETACMEOH_MQ1_Laubextrakt_110719133211.mzXML
ReAdW	--mzXML	WPETACMEOH_MQ_IT_Laubextrakt.raw	WPETACMEOH_MQ_IT_Laubextrakt.mzXML
ReAdW	--mzXML	WPETACMEOH_MQ_Laubextrakt.raw	WPETACMEOH_MQ_Laubextrakt.mzXML
