ReAdW	--mzXML	input.raw	output.mzXML
ReAdW	--mzXML	input.raw	output.mzXML
ReAdW	--mzXML	MAB91 (Bodenwasser_ev).raw             	MAB91 (Bodenwasser_ev).mzXML             
ReAdW	--mzXML	MAB92_Bodenwasser.raw	MAB92_Bodenwasser.mzXML
ReAdW	--mzXML	MAB93_Bodenwasser.raw                  	MAB93_Bodenwasser.mzXML                  
ReAdW	--mzXML	MAB94_Bodenwasser.raw	MAB94_Bodenwasser.mzXML
ReAdW	--mzXML	MAB94_WDH_Bodenwasser.raw              	MAB94_WDH_Bodenwasser.mzXML              
ReAdW	--mzXML	MSK1_Bodenwasser.raw	MSK1_Bodenwasser.mzXML
ReAdW	--mzXML	MSK2_Bodenwasser.raw                   	MSK2_Bodenwasser.mzXML                   
ReAdW	--mzXML	MSK3_Bodenwasser.raw                         	MSK3_Bodenwasser.mzXML                         
ReAdW	--mzXML	S4AB91_Bodenwasser.raw	S4AB91_Bodenwasser.mzXML
ReAdW	--mzXML	S4AB92_Bodenwasser.raw                 	S4AB92_Bodenwasser.mzXML                 
ReAdW	--mzXML	S4AB93_1_Bodenwasser.raw	S4AB93_1_Bodenwasser.mzXML
ReAdW	--mzXML	S4AB93_Bodenwasser.raw                 	S4AB93_Bodenwasser.mzXML                 
ReAdW	--mzXML	S4AB94_1_Bodenwasser.raw	S4AB94_1_Bodenwasser.mzXML
ReAdW	--mzXML	S4SK1_1_Bodenwasser.raw                	S4SK1_1_Bodenwasser.mzXML                
ReAdW	--mzXML	S4SK1_Bodenwasser.raw	S4SK1_Bodenwasser.mzXML
ReAdW	--mzXML	S4SK2_1_Bodenwasser.raw                	S4SK2_1_Bodenwasser.mzXML                
ReAdW	--mzXML	S4SK2_2_Bodenwasser.raw	S4SK2_2_Bodenwasser.mzXML
ReAdW	--mzXML	S4SK2_2_Bodenwasser_110718162836.raw   	S4SK2_2_Bodenwasser_110718162836.mzXML   
ReAdW	--mzXML	S4SK2_Bodenwasser.raw	S4SK2_Bodenwasser.mzXML
ReAdW	--mzXML	S4SK3_WDH_Bodenwasser.raw              	S4SK3_WDH_Bodenwasser.mzXML              
ReAdW	--mzXML	S4SK4_1_Bodenwasser.raw	S4SK4_1_Bodenwasser.mzXML
ReAdW	--mzXML	S4SK4_Bodenwasser_110718162836.raw  	S4SK4_Bodenwasser_110718162836.mzXML  
